spring:
  application:
    name: Pulse

server:
  ssl:
    key-store: classpath:certs/keystore.p12
    keystore-password: test1234
    key-store-type: PKCS12
    key-alias: mysslkey

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive.config: DEBUG